"""Adjust model nullability constraints

Revision ID: 349090d555d4
Revises: 821854adfb69
Create Date: 2025-04-30 10:39:51.343874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '349090d555d4'
down_revision: Union[str, None] = '821854adfb69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('platform_common', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sales', 'platform_listing_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales', 'platform_listing_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('sales', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('platform_common', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
