"""Add server_default to timestamp columns in models

Revision ID: 9316da015cd1
Revises: 6c97de0cfe06
Create Date: 2025-04-30 10:12:34.385034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9316da015cd1'
down_revision: Union[str, None] = '6c97de0cfe06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ebay_listings', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('platform_common', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('platform_common', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('sales', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('website_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('website_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('website_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('website_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True)
    op.alter_column('shipments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('shipments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('sales', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('products', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('platform_common', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('platform_common', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ebay_listings', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("(now() AT TIME ZONE 'utc'::text)"),
               existing_nullable=True)
    # ### end Alembic commands ###
