"""Add vendor and price columns to shopify_listings

Revision ID: c99ad3172b8c
Revises: b5adac874ba0
Create Date: 2025-06-05 16:44:29.513722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c99ad3172b8c'
down_revision: Union[str, None] = 'b5adac874ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopify_listings', sa.Column('vendor', sa.String(length=255), nullable=True))
    op.add_column('shopify_listings', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopify_listings', 'price')
    op.drop_column('shopify_listings', 'vendor')
    # ### end Alembic commands ###
