"""create_vr_accepted_brands_table

Revision ID: 99c07d825b2c
Revises: a117699444e2
Create Date: 2025-05-22 12:10:32.828279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99c07d825b2c'
down_revision: Union[str, None] = 'a117699444e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vr_accepted_brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vr_brand_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('name_normalized', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vr_accepted_brands_id'), 'vr_accepted_brands', ['id'], unique=False)
    op.create_index(op.f('ix_vr_accepted_brands_name'), 'vr_accepted_brands', ['name'], unique=True)
    op.create_index(op.f('ix_vr_accepted_brands_name_normalized'), 'vr_accepted_brands', ['name_normalized'], unique=True)
    op.create_index(op.f('ix_vr_accepted_brands_vr_brand_id'), 'vr_accepted_brands', ['vr_brand_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vr_accepted_brands_vr_brand_id'), table_name='vr_accepted_brands')
    op.drop_index(op.f('ix_vr_accepted_brands_name_normalized'), table_name='vr_accepted_brands')
    op.drop_index(op.f('ix_vr_accepted_brands_name'), table_name='vr_accepted_brands')
    op.drop_index(op.f('ix_vr_accepted_brands_id'), table_name='vr_accepted_brands')
    op.drop_table('vr_accepted_brands')
    # ### end Alembic commands ###