"""Initial database setup

Revision ID: d76101de8296
Revises: 
Create Date: 2025-02-02 16:44:04.855046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd76101de8296'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_import_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('successful_rows', sa.Integer(), nullable=True),
    sa.Column('failed_rows', sa.Integer(), nullable=True),
    sa.Column('error_log', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('brand_name', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('product_model', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('decade', sa.Integer(), nullable=True),
    sa.Column('finish', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_notax', sa.Float(), nullable=True),
    sa.Column('collective_discount', sa.Float(), nullable=True),
    sa.Column('offer_discount', sa.Float(), nullable=True),
    sa.Column('is_sold', sa.Boolean(), nullable=True),
    sa.Column('in_collective', sa.Boolean(), nullable=True),
    sa.Column('in_inventory', sa.Boolean(), nullable=True),
    sa.Column('in_reseller', sa.Boolean(), nullable=True),
    sa.Column('free_shipping', sa.Boolean(), nullable=True),
    sa.Column('buy_now', sa.Boolean(), nullable=True),
    sa.Column('show_vat', sa.Boolean(), nullable=True),
    sa.Column('local_pickup', sa.Boolean(), nullable=True),
    sa.Column('available_for_shipment', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('video_url', sa.String(), nullable=True),
    sa.Column('external_link', sa.String(), nullable=True),
    sa.Column('processing_time', sa.Integer(), nullable=True),
    sa.Column('platform_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('platform_name', sa.String(), nullable=True),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('listing_url', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=True),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('platform_specific_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_listings')
    op.drop_table('products')
    op.drop_table('csv_import_logs')
    # ### end Alembic commands ###
