"""Update timestamp defaults (compare server default)

Revision ID: eb774d2b4f5c
Revises: 3e399e66c3a0
Create Date: 2025-04-29 15:52:31.487267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eb774d2b4f5c'
down_revision: Union[str, None] = '3e399e66c3a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted for timestamps! ###
    
    # Keep server_default=None for non-timestamp columns as generated
    op.alter_column('ebay_listings', 'quantity_sold',
               existing_type=sa.INTEGER(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('platform_common', 'platform_specific_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'inventory_quantity',
               existing_type=sa.INTEGER(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'has_inventory',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'offers_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'is_auction',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'watch_count',
               existing_type=sa.INTEGER(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'extended_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'handmade',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('vr_listings', 'in_collective',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('vr_listings', 'in_inventory',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('vr_listings', 'in_reseller',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('vr_listings', 'show_vat',
               existing_type=sa.BOOLEAN(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('vr_listings', 'inventory_quantity',
               existing_type=sa.INTEGER(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('vr_listings', 'extended_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None, 
               existing_nullable=True)

    # Set correct server_default for timestamp columns
    utc_now = sa.text("now() at time zone 'utc'") # PostgreSQL specific timezone aware now

    op.alter_column('category_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
    op.alter_column('category_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
               
    op.alter_column('ebay_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
    op.alter_column('ebay_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
    op.alter_column('ebay_listings', 'last_synced_at', # Assuming this should also be UTC now default
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)

    op.alter_column('reverb_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
    op.alter_column('reverb_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)

    op.alter_column('shipping_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)

    op.alter_column('vr_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
    op.alter_column('vr_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=utc_now, # Set correct default
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - manually adjusted for timestamps! ###

    # Revert timestamp columns server_default to None (matching original autogen upgrade state)
    op.alter_column('vr_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('vr_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('reverb_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('ebay_listings', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('ebay_listings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('ebay_listings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('category_mappings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)
    op.alter_column('category_mappings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None, 
               existing_nullable=True)

    # Restore other server defaults based on original autogen downgrade
    op.alter_column('vr_listings', 'extended_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('vr_listings', 'inventory_quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('vr_listings', 'show_vat',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('vr_listings', 'in_reseller',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('vr_listings', 'in_inventory',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('vr_listings', 'in_collective',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'handmade',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'extended_attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'watch_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'view_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'is_auction',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'offers_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'has_inventory',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('reverb_listings', 'inventory_quantity',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('platform_common', 'platform_specific_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=True)
    op.alter_column('ebay_listings', 'quantity_sold',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    # ### end Alembic commands ###
