"""Verify model timestamp server defaults

Revision ID: 821854adfb69
Revises: e2f48d8189d4
Create Date: 2025-04-30 10:22:42.389165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '821854adfb69'
down_revision: Union[str, None] = 'e2f48d8189d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
