"""Add server_default to timestamp columns in models last couple of stragglers

Revision ID: c363c35d0a10
Revises: 9316da015cd1
Create Date: 2025-04-30 10:22:11.858242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c363c35d0a10'
down_revision: Union[str, None] = '9316da015cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ebay_listings', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text("now() AT TIME ZONE 'utc'"),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('shipping_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('shipping_profiles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('ebay_listings', 'last_synced_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
    # ### end Alembic commands ###
